
server:
  port: 8084
spring:
  application:
    name: happy-learning-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: happy-learning-arithmetic
          uri: lb://happy-learning-arithmetic
          predicates:
            - Path=/arithmetic/**
        - id: happy-learning-arithmeticgamification
          uri: lb://happy-learning-arithmeticgamification
          predicates:
            - Path=/gamification/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.56.1:8099/eureka/